name: spinal_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.1.4
  animated_text_kit: ^1.3.0
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  firebase_database: ^3.1.1
  firebase_messaging: ^6.0.13
  modal_progress_hud: ^0.1.3
  geolocator: ^3.0.1
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.6.0
  flutter_local_notifications: ^1.2.1
  provider: ^4.0.4
  custom_splash: ^0.0.2
  drag_select_grid_view: ^0.1.1
  app_settings: ^3.0.1
  flappy_search_bar: ^1.7.2
  settings_ui: ^0.2.0
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_native_splash:
  image: images/splash.png
#  color: "#ffffff"
  fill: false

flutter:
  uses-material-design: true
  assets:
    - images/